// <auto-generated />
using System;
using System.Collections.Generic;
using Cliptok;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Cliptok.Migrations
{
    [DbContext(typeof(CliptokDbContext))]
    [Migration("20250708222729_bulkmessagelogstore")]
    partial class bulkmessagelogstore
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BulkMessageLogStoreCachedDiscordUser", b =>
                {
                    b.Property<int>("BulkMessageLogsId")
                        .HasColumnType("integer");

                    b.Property<decimal>("UsersId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("BulkMessageLogsId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("BulkMessageLogStoreCachedDiscordUser");
                });

            modelBuilder.Entity("Cliptok.Types.Models+BulkMessageLogStore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DiscordUrl")
                        .HasColumnType("text");

                    b.Property<string>("PasteUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("BulkMessageLogStore");
                });

            modelBuilder.Entity("Cliptok.Types.Models+CachedDiscordMessage", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)");

                    b.PrimitiveCollection<List<string>>("AttachmentURLs")
                        .HasColumnType("text[]");

                    b.Property<decimal>("ChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("UserId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("Cliptok.Types.Models+CachedDiscordUser", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<bool>("IsBot")
                        .HasColumnType("boolean");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BulkMessageLogStoreCachedDiscordUser", b =>
                {
                    b.HasOne("Cliptok.Types.Models+BulkMessageLogStore", null)
                        .WithMany()
                        .HasForeignKey("BulkMessageLogsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cliptok.Types.Models+CachedDiscordUser", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Cliptok.Types.Models+CachedDiscordMessage", b =>
                {
                    b.HasOne("Cliptok.Types.Models+CachedDiscordUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
